version: "3.9" 
services:
  db:
    #build: 
      #context: .
      #dockerfile: ./docker/docker-db/Dockerfile
      #shm_size: '4gb'
    image: sarrez99/mlopen:mlopen_db
    shm_size: '4gb'
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
  web:
    #build: 
      #context: .
      #dockerfile: ./docker/docker-web/Dockerfile
      #shm_size: '4gb'
    image: sarrez99/mlopen:mlopen_web
    shm_size: '4gb'
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate --run-syncdb &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: sarrez99/mlopen:mlopen_redis

  celery:
    restart: always
    #build: 
      #context: .
      #dockerfile: ./docker/docker-web/Dockerfile
      #shm_size: '4gb'
    image: sarrez99/mlopen:mlopen_celery
    shm_size: '4gb'
    command: celery -A mlopen worker -l info

    volumes: 
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
